window.ENV = {
  FIREBASE_API_KEY: "YOUR_FIREBASE_API_KEY",
  FIREBASE_AUTH_DOMAIN: "YOUR_FIREBASE_AUTH_DOMAIN",
  FIREBASE_PROJECT_ID: "YOUR_FIREBASE_PROJECT_ID",
  FIREBASE_STORAGE_BUCKET: "YOUR_FIREBASE_STORAGE_BUCKET",
  FIREBASE_MESSAGING_SENDER_ID: "YOUR_FIREBASE_MESSAGING_SENDER_ID",
  FIREBASE_APP_ID: "YOUR_FIREBASE_APP_ID",
  FIREBASE_MEASUREMENT_ID: "YOUR_FIREBASE_MEASUREMENT_ID",
  
  GOOGLE_CLIENT_ID: "YOUR_GOOGLE_CLIENT_ID",
  GOOGLE_API_KEY: "YOUR_GOOGLE_API_KEY",
  
  GEMINI_API_KEY: "YOUR_GEMINI_API_KEY"
};
